# Generated by Django 4.0.4 on 2022-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': (
                'nome',), 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf',
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='rg',
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
    ]
