# Generated by Django 4.0.4 on 2022-07-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_fornecedor_options'),
        ('crm', '0002_alter_fornecedor_options_alter_cliente_cnpj_and_more'),
    ]

    operations = [
    ]
