# Generated by Django 4.0.4 on 2022-05-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor')),
                ('created_user', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(max_length=100, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('cliente', models.ManyToManyField(blank=True, to='clientes.clientes')),
                ('patrimonio', models.ManyToManyField(blank=True, to='produtos.patrimonio')),
                ('produtos', models.ManyToManyField(blank=True, to='produtos.produtos')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['created_at'],
            },
        ),
    ]
