# Generated by Django 4.0.4 on 2022-05-30 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentos',
            name='patrimonio',
        ),
        migrations.AddField(
            model_name='orcamentositens',
            name='patrimonio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='patrimonio_orcamentos', to='produtos.patrimonio'),
        ),
        migrations.RemoveField(
            model_name='orcamentos',
            name='cliente',
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='cliente_orcamentos', to='clientes.clientes'),
        ),
    ]
