# Generated by Django 4.0.4 on 2022-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_alter_orcamentos_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentos',
            name='checkbox',
            field=models.BooleanField(max_length=10, verbose_name='Excluir'),
        ),
    ]
