# Generated by Django 4.0.4 on 2022-07-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modificado em')),
                ('deleted', models.DateTimeField(
                    blank=True, null=True, verbose_name='deletado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(
                    default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deletado por')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modificado em')),
                ('deleted', models.DateTimeField(
                    blank=True, null=True, verbose_name='deletado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(
                    default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deletado por')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modificado em')),
                ('deleted', models.DateTimeField(
                    blank=True, null=True, verbose_name='deletado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(
                    default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('codigo', models.PositiveIntegerField(verbose_name='Código')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Preço compra')),
                ('preco_diaria', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Preço Diária')),
                ('estoque_minimo', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Estoque Mínimo')),
                ('estoque_atual', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Estoque Atual')),
                ('categoria', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='produto.categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deletado por')),
                ('marca', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='produto.marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modificado em')),
                ('deleted', models.DateTimeField(
                    blank=True, null=True, verbose_name='deletado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(
                    default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('titulo', models.CharField(max_length=100,
                 unique=True, verbose_name='titulo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deletado por')),
                ('produto', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ('titulo',),
            },
        ),
    ]
