# Generated by Django 4.0.4 on 2022-07-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('created_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(
                    max_length=100, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=200)),
                ('created_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(
                    max_length=100, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('marca', 'modelo'),
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_Compra', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Preço compra')),
                ('valor_Locacao', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Preço Diária')),
                ('estoque_minimo', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Estoque minimo')),
                ('qnt_estoque', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Qnt em Estoque')),
                ('estoque_total', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Estoque total')),
                ('created_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(
                    max_length=100, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('id_grupo', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='produto.categoria')),
                ('id_marca', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='produto.marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('id_grupo', 'id_marca', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(blank=True, max_length=100,
                 null=True, unique=True, verbose_name='patrimônio')),
                ('produto', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='produto.produto')),
            ],
            options={
                'ordering': ('patrimonio',),
            },
        ),
    ]
