# Generated by Django 4.0.4 on 2022-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrimonio',
            old_name='produtoPatrimonio',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='patrimonio',
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name='patrimônio'),
        ),
    ]
