# Generated by Django 4.0.4 on 2022-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
