# Generated by Django 4.0.4 on 2022-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='titulo',
            field=models.CharField(
                max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
