# Generated by Django 4.0.4 on 2022-07-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modificado em')),
                ('deleted', models.DateTimeField(
                    blank=True, null=True, verbose_name='deletado em')),
                ('checkbox', models.BooleanField(
                    max_length=10, verbose_name='Excluir')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='cliente_orcamentos', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Valor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='orcamentos', to='orcamento.orcamento')),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='patrimonio_orcamentos', to='produto.patrimonio')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='produto_orcamentos', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Orçamento Item',
                'verbose_name_plural': 'Orçamento Itens',
                'ordering': ('-pk',),
            },
        ),
    ]
