# Generated by Django 4.0.4 on 2022-06-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(
                    max_length=10, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='cliente_orcamentos', to='cliente.clientes')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrcamentosItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Valor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='orcamentos', to='orcamento.orcamentos')),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='patrimonio_orcamentos', to='produto.patrimonio')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='produto_orcamentos', to='produto.produtos')),
            ],
            options={
                'verbose_name': 'Orçamento Item',
                'verbose_name_plural': 'Orçamento Itens',
                'ordering': ('-pk',),
            },
        ),
    ]
