# Generated by Django 4.0.4 on 2022-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitens',
            name='valor',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
