# Generated by Django 4.0.4 on 2022-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_alter_orcamentoitens_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitens',
            name='periodo',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='Período'),
        ),
    ]
