# Generated by Django 4.0.4 on 2022-07-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_orcamentoitens_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamentoitens',
            options={'ordering': ('pk',), 'verbose_name': 'Orçamento Item',
                     'verbose_name_plural': 'Orçamento Itens'},
        ),
    ]
