# Generated by Django 4.0.4 on 2022-07-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_orcamento_desconto_orcamentoitens_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='periodo',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='Período (em dias)'),
        ),
    ]
