# Generated by Django 4.0.4 on 2022-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0008_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='periodo',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Período (em dias)'),
        ),
    ]
