# Generated by Django 4.0.4 on 2022-07-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_alter_orcamento_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='orcamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='contrato', to='orcamento.orcamento', verbose_name='orçamento'),
        ),
    ]
