# Generated by Django 4.0.4 on 2022-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0010_alter_contrato_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[(
                'p', 'Pendente'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='p', max_length=1),
        ),
    ]
