# Generated by Django 4.0.6 on 2022-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0011_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[(
                'p', 'Pendente'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='p', max_length=1),
        ),
    ]
