# Generated by Django 4.0.4 on 2022-07-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('tipo', 'nome', 'nome_fantasia'),
                     'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nomeFantasia',
            new_name='nome_fantasia',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='razaoSocial',
            new_name='razao_social',
        ),
    ]
