# Generated by Django 4.0.4 on 2022-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='checkbox',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='address',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='address_number',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='city',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complement',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='country',
            field=models.CharField(
                blank=True, default='Brasil', max_length=50, null=True, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='district',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='exist_deleted',
            field=models.BooleanField(
                default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), (
                'PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
