# Generated by Django 4.0.4 on 2022-07-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='RG'),
        ),
    ]
