# Generated by Django 4.0.4 on 2022-05-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('created_user', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(max_length=100, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=200)),
                ('created_user', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(max_length=100, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('marca', 'modelo'),
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_Compra', models.CharField(max_length=100, verbose_name='Preço compra')),
                ('valor_Locacao', models.CharField(max_length=100, verbose_name='Preço Diária')),
                ('estoque_minimo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estoque minimo')),
                ('qnt_estoque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qnt em Estoque')),
                ('estoque_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estoque total')),
                ('created_user', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(max_length=100, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('id_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria')),
                ('id_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('id_grupo', 'id_marca', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=100, unique=True)),
                ('created_user', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_user', models.CharField(blank=True, max_length=100, null=True)),
                ('checkbox', models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('produtoPatrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='produtos.produtos')),
            ],
            options={
                'ordering': ('patrimonio',),
            },
        ),
    ]
