# Generated by Django 4.0.4 on 2022-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='estoque_minimo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estoque minimo'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='estoque_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estoque total'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qnt_estoque',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qnt em Estoque'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor_Compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço compra'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor_Locacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço Diária'),
        ),
    ]
