# Generated by Django 4.0.4 on 2022-06-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtos_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='patrimonio',
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True),
        ),
    ]
