# Generated by Django 4.0.4 on 2022-06-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_patrimonio_patrimonio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimonio',
            name='checkbox',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='delete_user',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='updated_at',
        ),
    ]
